
# My configs
## alias
alias pc="proxychains4"
alias vim="nvim"
alias avgi="awk '{cnt += 1; sum += \$1};END {printf \"%d\n\", sum/cnt}'"
alias avgf="awk '{cnt += 1; sum += \$1};END {printf \"%.2lf\n\", sum/cnt}'"
alias sumn="awk '{sum += \$1};END {print sum}'"
alias vimrc="nvim ~/.config/nvim/init.vim"
alias zshrc="nvim ~/.zshrc"
